[WIP] convert test_projection to C++
AMReX-Astro/MAESTROeX pull request #307
Opened 2021-12-21 16:02 UTC by zingale

2021-12-23 21:51 UTC, doreenfan requested changes
There is a typo when computing x: `prob_lo[2]` should be `prob_lo[0]`. 
And z should only be computed when `AMREX_SPACEDIM == 3`.

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = static_cast<Real>(i) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    vmac(i,j,k) =
vmac -> vmac_arr

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = static_cast<Real>(i) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = static_cast<Real>(i) * dx[0] + prob_lo[2];
prob_lo[2] -> prob_lo[0]

2021-12-23 21:51 UTC, doreenfan commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
Add `#if AMREX_SPACEDIM == 3` around `Real z = ...`

2021-12-23 21:53 UTC, doreenfan commented
We also need to include `maestro.max_step = 1` in every input file because either `max_step` or `stop_time` needs to be given for the code to run.

2022-01-04 16:06 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:07 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM == 3)
                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:07 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = static_cast<Real>(i) * dx[0] + prob_lo[2];
```suggestion
                    Real x = static_cast<Real>(i) * dx[0] + prob_lo[0];
```

2022-01-04 16:07 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:08 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:10 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:11 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:11 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    vmac(i,j,k) =
```suggestion
                    vmac_arr(i,j,k) =
```

2022-01-04 16:11 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:12 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:12 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +#endif
```suggestion
#if (AMREX_SPACEDIM == 3)
                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:12 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +#endif
```suggestion
#if (AMREX_SPACEDIM == 3)
                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:13 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:13 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:14 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:14 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = static_cast<Real>(i) * dx[0] + prob_lo[2];
```suggestion
                        Real x = static_cast<Real>(i) * dx[0] + prob_lo[0];
```

2022-01-04 16:14 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                        Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:15 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                        Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:16 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:18 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 16:19 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
```suggestion
#if (AMREX_SPACEDIM==3)
                    Real z = (static_cast<Real>(k)+0.5_rt) * dx[2] + prob_lo[2];
#endif
```

2022-01-04 16:19 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    vmac(i,j,k) =
```suggestion
                    vmac_arr(i,j,k) =
```

2022-01-04 16:19 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[2];
```suggestion
                    Real x = (static_cast<Real>(i)+0.5_rt) * dx[0] + prob_lo[0];
```

2022-01-04 17:49 UTC, ajnonaka commented on Exec/unit_tests/test_projection/MaestroEvolve.cpp
> +#if AMREX_SPACEDIM == 3
```suggestion
#if (AMREX_SPACEDIM == 3)
```

2022-01-05 00:32 UTC, doreenfan approved these changes

2023-05-02 20:00 UTC, merged